export const DISTRICT = {
    Malaysia: ['All'],
    Johor: ['All', 'Batu Pahat', 'Johor Bahru', 'Kluang', 'Kulai', 'Mersing', 'Muar', 'Pontian', 'Segamat', 'Kota Tinggi', 'Tangkak'],
    Kedah: ['All', 'Baling', 'Kota Setar', 'Kuala Muda', 'Kubang Pasu', 'Kulim', 'Langkawi', 'Padang Terap', 'Pendang', 'Bandar Bahru',
        'Sik', 'Yan'],
    Kelantan: ['All', 'Bachok', 'Gua Musang', 'Kota Bharu', 'Tanah Merah', 'Kuala Krai', 'Pasir Mas', 'Pasir Puteh', 'Tumpat', 'Jeli',
        'Machang'],
    Melaka: ['All', 'Alor Gajah', 'Jasin', 'Melaka Tengah'],
    NegeriSembilan: ['All', 'Jelebu', 'Jempol', 'Kuala Pilah', 'Port Dickson', 'Rembau', 'Seremban', 'Tampin'],
    Pahang: ['All', 'Bentong', 'Jerantut', 'Bera', 'Raub', 'Lipis', 'Cameron Highlands', 'Kuantan', 'Maran', 'Pekan', 'Temerloh',
        'Rompin'],
    PulauPinang: ['All', 'Seberang Perai Tengah', 'Timur Laut', 'Seberang Perai Selatan', 'Barat Daya', 'Seberang Perai Utara'],
    Perak: ['All', 'Hilir Perak', 'Kinta', 'Perak Tengah', 'Larut, Matang, Selama', 'Manjung', 'Kuala Kangsar', 'Hulu Perak', 'Kerian',
        'Batang Padang', 'Muallim', 'Kampar'],
    Perlis: ['All'],
    Selangor: ['All', 'Petaling', 'Hulu Langat', 'Gombak', 'Klang', 'Kuala Selangor', 'Sepang', 'Kuala Langat', 'Sabak Bernam', 'Hulu Selangor'],
    Terengganu: ['All', 'Besut', 'Dungun', 'Kemaman', 'Kuala Terengganu', 'Marang', 'Kuala Nerus', 'Setiu', 'Hulu Terengganu'],
    Sabah: ['All', 'Beufort', 'Kinabatangan', 'Kota Belud', 'Kota Kinabalu', 'Kunak', 'Lahad Datu', 'Papar', 'Putatan', 'Sandakan',
        'Semporna', 'Sipitang', 'Tawau', 'Ranau', 'Tuaran', 'Keningau', 'Kota Marudu', 'Kudat', 'Nabawan', 'Pitas', 'Tambunan', 'Tenom',
        'Penampang', 'Kuala Penyu', 'Tongod', 'Beluran'],
    Sarawak: ['All', 'Kapit', 'Sri Aman', 'Asajaya', 'Baram', 'Bau', 'Belaga', 'Dalat', 'Daro', 'Julau', 'Kanowit', 'Lundu', 'Matu',
        'Song', 'Saratok', 'Lubok Antu', 'Kuching', 'Kota Samarahan', 'Limbang', 'Serian', 'Miri', 'Sarikei', 'Bintulu', 'Simunjan',
        'Mukah', 'Betong', 'Lawas', 'Sibu', 'Meradong', 'Pakan', 'Tatau', 'Selangau'],
    WilayahPersekutuanKualaLumpur: ['All', 'Cheras', 'Kepong', 'Lembah Pantai', 'Titiwangsa'],
    WilayahPersekutuanLabuan: ['All'],
    WilayahPersekutuanPutrajaya: ['All'],
}